### ISSUE TITLE
java invoke fails on 0.9 with no information

### ISSUE THREAD

**Issue by madisp** [square/gradle-dependencies-sorter#122]
After upgrading to 0.9 running on one of the modules fails with non-zero exit value 2:

```
./gradlew :gate:gate:checkSortDependencies

Type-safe project accessors is an incubating feature.
> Task :gate:gate:checkSortDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gate:gate:checkSortDependencies'.
> Process 'command '/Users/madis/.asdf/installs/java/zulu-21.30.15/zulu-21.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

I ran with `--debug`, hoping to get more info, but not much more there:

```
2024-10-12T10:56:09.175+0300 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command '/Users/madis/.asdf/installs/java/zulu-21.30.15/zulu-21.jdk/Contents/Home/bin/java''. Working directory: /Volumes/src/warp-speed/gate/gate Command: /Users/madis/.asdf/installs/java/zulu-21.30.15/zulu-21.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp /Users/madis/.gradle/caches/modules-2/files-2.1/com.squareup/sort-gradle-dependencies-app/0.9/9bacf36ccab08ee75e854ea1a9909c0f59c85c64/sort-gradle-dependencies-app-0.9-all.jar com.squareup.sort.MainKt /Volumes/src/warp-speed/gate/gate/build.gradle.kts --mode check --context gradle
2024-10-12T10:56:09.175+0300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2024-10-12T10:56:09.175+0300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/Users/madis/.asdf/installs/java/zulu-21.30.15/zulu-21.jdk/Contents/Home/bin/java'.
2024-10-12T10:56:09.179+0300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2024-10-12T10:56:09.179+0300 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2024-10-12T10:56:09.179+0300 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Users/madis/.asdf/installs/java/zulu-21.30.15/zulu-21.jdk/Contents/Home/bin/java''
2024-10-12T10:56:10.380+0300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
```

**Comment by madisp** [comment]
ok, the dependency sort rules in that module changed - after running `./gradlew :gate:gate:sortDependencies` it passed. But a message or something would've been helpful :)

**Comment by autonomousapps** [comment]
> But a message or something would've been helpful :)

Huh... it's supposed to!

**Comment by madisp** [comment]
hmm, I can dig some more as I can reproduce this easily. Which part is supposed to do the printing, the wrapped CLI (`com.squareup.sort.MainKt`) or the Gradle plugin?

**Comment by utwyko** [comment]
I'm seeing the same thing (Running on Temurin JDK 21. 0.5). The last version that prints the output is 0.6. Based on the changelog, my guess would be that the switch to Clikt CLI is the culprit.

**Comment by autonomousapps** [comment]
This should now be fixed with the 0.10 release! Thanks for the reports <3

**Comment by utwyko** [comment]
Unfortunately I'm still seeing this issue in 0.10. It happens both when running `checkSortDependencies` on a specific module or running it on the root project.

I do see error messages on the Antlr codegen version not matching the runtime version. but I don't see how that would impact this issue.

*0.6 output*
 ```
./gradlew :<REDACTED_MODULE>:checkSortDependencies
Sorting '/<REDACTED_PATH>/<REDACTED_MODULE>/build.gradle' using mode 'check'.
[main] INFO Sorter - Sorting build.gradle(.kts) scripts in the following paths: /<REDACTED_PATH>/<REDACTED_MODULE>/build.gradle, false
[main] INFO Sorter - It took 15 ms to find 1 build scripts.
[main] INFO Sorter - Failed! 1 scripts are not ordered correctly.
Metrics:
  Not sorted:     1
  Already sorted: 0
  Parse errors:   0

Fix by running
./scripts/sort build.gradle

Check duration: 40 ms.

[main] INFO Sorter - Operation took 68 ms
[main] INFO Sorter - See log file at /var/folders/r7/3_pf511s6d72x6xlthvf0q_m0000gq/T/13263464465885040162.tmp 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':<REDACTED_MODULE>:checkSortDependencies'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/bin/java'' finished with non-zero exit value 3
```

*0.10 output*
```
./gradlew :<REDACTED_MODULE>:checkSortDependencies

> Task :<REDACTED_MODULE>:checkSortDependencies FAILED
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.13.1
ANTLR Runtime version 4.10.1 used for parser compilation does not match the current runtime version 4.13.1
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.13.1
ANTLR Runtime version 4.10.1 used for parser compilation does not match the current runtime version 4.13.1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':<REDACTED_MODULE>:checkSortDependencies'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

Thanks for your assistance on this and the great work on the plugin.

**Comment by autonomousapps** [comment]
The issue is actually that we disabled verbose output by default. In larger repos it was leading to a lot of console output. See [here](https://github.com/square/gradle-dependencies-sorter/blob/main/sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt#L51) and [here](https://github.com/square/gradle-dependencies-sorter/blob/main/sort-dependencies-gradle-plugin/src/main/kotlin/com/squareup/sort/SortDependenciesTask.kt#L56).

You can re-enable verbose mode like so

```kotlin
// foo/build.gradle.kts
tasks.sortDependencies {
  verbose = true
}
```
That said, we should put that on the `sortDependencies` extension too. Also, that only works for a single build script and not if you want to enable verbose mode globally. If you want the latter, please open a new issue as a feature request, and thanks.

**Comment by autonomousapps** [comment]
Actually I'm looking at the code now and it _should_ print something if there's an error. So that is definitely a bug.

**Comment by utwyko** [comment]
Perfect, thanks for the effort!

**Comment by madisp** [comment]
I think the info I want to see should be printed by [this line](https://github.com/square/gradle-dependencies-sorter/blob/b71c79693766bbab4f9fde8bbe6e311df88d0e99/app/src/main/kotlin/com/squareup/sort/SortCommand.kt#L219).

What sort of slf4j logger are you using, is it sending `.info()` to stdout?

**Comment by autonomousapps** [comment]
> I think the info I want to see should be printed by [this line](https://github.com/square/gradle-dependencies-sorter/blob/b71c79693766bbab4f9fde8bbe6e311df88d0e99/app/src/main/kotlin/com/squareup/sort/SortCommand.kt#L219).
> 
> What sort of slf4j logger are you using, is it sending `.info()` to stdout?

Then I think you should configure it to use verbose mode per [this](https://github.com/square/gradle-dependencies-sorter/issues/122#issuecomment-2451006693).

The logger is a [wrapper](https://github.com/square/gradle-dependencies-sorter/blob/b71c79693766bbab4f9fde8bbe6e311df88d0e99/app/src/main/kotlin/com/squareup/log/DelegatingLogger.kt) around slf4j that delegates to the base logger.
